apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubermatic-all-project-viewer
rules:
- apiGroups:
  - kubermatic.k8c.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-reader
  namespace: test-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zabbix-reader-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubermatic-all-project-viewer
subjects:
- kind: ServiceAccount
  name: zabbix-reader
  namespace: test-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-reader-secret
  namespace: test-sa
  annotations:
    kubernetes.io/service-account.name: zabbix-reader
type: kubernetes.io/service-account-token